[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "distributed-blockchain-intelligence"
version = "0.1.0"
dependencies = [
     "psycopg[binary]"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "pytest",
]